name: release

on:
  schedule:
    - cron: '0 0 */1 * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Static Curl
        run: |
          ./build.sh
          if [ -f "curl/mykey.asc" ] ; then
            git config --global user.name  "LubinLew"
            git config --global user.email "lgbxyz@gmail.com"
            git add version.txt
            VERSION=`cat version.txt`
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "GOON=true" >> $GITHUB_ENV
            git commit -m "curl ${VERSION}"
            git push
          else
            echo "GOON=false" >> $GITHUB_ENV
          fi

      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        if: env.GOON == 'true'
        with:
          tag: ${{env.VERSION}}
          message: "static curl ${{env.VERSION}}"

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: env.GOON == 'true'
        with:
          tag: ${{env.VERSION}}
          name: "static-curl-${{env.VERSION}}"
          artifacts: "curl/*.exe,curl/*.nonstrip"
          bodyFile: "curl/release.md"
          token: ${{ secrets.GITHUB_TOKEN }}
